"""rename address

Revision ID: 11320048283a
Revises: 4679494ec331
Create Date: 2024-10-07 18:00:29.337900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11320048283a'
down_revision = '4679494ec331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
